### ISSUE TITLE
ZIP 320 Implementation

### ISSUE THREAD

**Issue by zancas** [zingolabs/zingolib#1369]
## Goal

The purpose of this tracking issue is to manage the efficient implementation of 320.

### Objectives:
1.  Converge LRZ and `zingolib` to the best distance for rapid implementation of 320
2.  Provide functionality to unblock mobile developers allowing them to test UI/UX and Front End Test (FET) for 320 ASAP
3.  Implement and test 320

### Subtasks
- [ ] manage all dependencies such that 1. is rapidly achievable
- [ ] ~#1376~
- [ ]  produce a test showing parse recognizes address types, including TEX
- [ ] produce a test showing multi-step transaction created when TEX is parsed

Currently tagged PRs:

https://github.com/zingolabs/zingolib/pulls?q=is%3Apr+is%3Aopen+label%3A320

**Comment by pacu** [comment]
Some things I’ve seen in other wallets that must be taken into consideration:
- don’t show memos on Tex 
- ~account for 2x fees~
- prepare to receive 2 transactions as a result 
- ~librustzcash uses the proposal API (I think you already do)~
- resubmit both tx on expiry (Zashi does this)
